title: Jim Knochelmann
description: "DevSecOps Engineer | Cloud Security Expert | Automation Enthusiast"
url: "https://uncle13013.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author details (commented out to remove from footer)
# author:
#   name: "Jim Knochelmann"
#   email: "j.knochelmann@gmail.com"
  
# Social links (commented out to remove from footer)
# github_username: uncle13013
# linkedin_username: jim-knochelmann

# Navigation
header_pages:
  - index.md
  - about.md
  - skills.md
  - portfolio.md
  - blog.md
  - contact.md

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.gemspec"
