title: Jim Knochelmann
description: "DevSecOps Engineer | Cloud Security Expert | Automation Enthusiast"
url: "https://uncle13013.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author details
author:
  name: "Jim Knochelmann"
  email: "your.email@domain.com"
  
# Social links
github_username: uncle13013
linkedin_username: uncle13013
twitter_username: your_twitter

# Navigation
header_pages:
  - index.md
  - about.md
  - skills.md
  - portfolio.md
  - blog.md
  - contact.md

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.gemspec"
